import matplotlib.pyplot as plt

from koopmans.io import read

# Load the workflow
wf = read('cri3.pkl')

# The band structures were generated by the last four steps in the workflow
procs = wf.processes[-4:]

# Loop over the four sets of band structures and shift them all so that the VBM is zero
vbm = procs[0].outputs.band_structure._energies.max()
band_structures = []
for proc in procs:
    bs = proc.outputs.band_structure
    bs_shifted = bs.subtract_reference(vbm)
    band_structures.append(bs_shifted)

# Plot the band structures
ax = band_structures[0].plot(label='spin up', color='tab:red', ls="-")
ax = band_structures[1].plot(ax=ax, color='tab:red', ls="-")
ax = band_structures[2].plot(ax=ax, label='spin down', color='tab:blue', ls="-")
ax = band_structures[3].plot(ax=ax, color='tab:blue', ls="-")

ax.legend(loc='lower right', ncol=2, bbox_to_anchor=(1, 1))
ax.set_ylim([-5, 5])

plt.savefig('cri3_bandstructures.png')
