clean :
	/bin/rm -fr example*/*.wout  \
	example*/UNK*   \
	example*/*.mmn    \
        example*/*.amn    \
        example*/*.eig    \
        example*/*.nnkp    \
        example*/*.wout   \
        example*/*.out   \
        example*/*.save    \
        example*/*.wfc  \
        example*/*.xsf \
	example*/*.chk \
	example*/*.igk \
	example*/*_band.*
   
	

