name: "Build docs"
on:
   pull_request:
      branches:
         - master
      paths:
         - "docs/**"
   push:
      branches:
         - master
         - "docs/**"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
         python-version: '3.x'
    - name: Install dependencies
      run: |
         python -m pip install --upgrade pip
         pip install -e .[docs]
    - uses: actions/checkout@v3
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
