name: "Build docs"
on:
   pull_request:
      branches:
         - master
      paths:
         - "docs/**"
   push:
      branches:
         - master
         - "docs/**"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
