name: flake8 Lint

on:
   pull_request:
      branches:
         - master
   push:
      branches:
         - master

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
            plugins: "flake8-pyproject flake8-docstrings flake8-warnings flake8-builtins"
