name: Build QE

on:
   pull_request:
      branches:
         - master
      paths:
         - 'quantum_espresso/qe_koopmans/**'
   push:
      branches:
         - master
      paths:
         - 'quantum_espresso/qe_koopmans/**'

jobs:
   gfortran:
      runs-on: ubuntu-latest
      steps:
         - name: Set up git user
           run: |
              git config --global user.name "koopmans-tester"
              git config --global user.email ${{ secrets.KOOPMANS_TESTER_EMAIL }}
         - name: Checkout
           uses: actions/checkout@v2
           with:
              submodules: true
              ssh-known-hosts: 'gitlab.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAfuCHKVTjquxvt6CM6tdG4SLp1Btn/nOeHHE5UOzRdf'
              ssh-strict: false
              ssh-key: ${{ secrets.KOOPMANS_TESTER_PRIVATE_KEY }}
         - name: Install dependencies
           run: |
              sudo apt-get update
              sudo apt-get install gfortran libopenmpi-dev libblas-dev liblapack-dev fftw3-dev
         - name: Configure qe_koopmans
           run: |
              make configure_6 MPIF90=mpif90
         - name: Build qe_koopmans
           run: |
              make espresso_6 MPIF90=mpif90

