name: Build QE

on:
   pull_request:
      branches:
         - master
      paths:
         - 'quantum_espresso/qe_koopmans/**'
   push:
      branches:
         - master
      paths:
         - 'quantum_espresso/qe_koopmans/**'

jobs:
   gfortran:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v2
           with:
              submodules: true
         - name: Install dependencies
           run: |
              sudo apt-get update
              sudo apt-get install gfortran libopenmpi-dev libblas-dev liblapack-dev fftw3-dev
         - name: Configure qe_koopmans
           run: |
              make configure_6 MPIF90=mpif90
         - name: Build qe_koopmans
           run: |
              make espresso_6 MPIF90=mpif90

