name: pylint

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[lint,test,docs]
      - name: Run pylint checks
        run: |
          set -e
          pylint --enable=all --fail-on=W4901,W4902,W4903,W4904,W4905,W4906 $(git ls-files '*.py')
